"""empty message

Revision ID: 4ddfed5ae14f
Revises: 
Create Date: 2019-05-23 14:35:36.696978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddfed5ae14f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('boro', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cuisine_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('violation_code', sa.String(), nullable=True),
    sa.Column('violation_desc', sa.String(), nullable=True),
    sa.Column('critical_flag', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('grade_date', sa.String(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('inspection_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspections')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
